export const data = [
    {
        "alwaysOnTop": false,
        "focused": false,
        "height": 1415,
        "id": 1388900961,
        "incognito": false,
        "left": 1512,
        "state": "maximized",
        "tabs": [
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.overleaf.com/favicon.ico",
                "groupId": 1014996195,
                "height": 1328,
                "highlighted": false,
                "id": 1388904518,
                "incognito": false,
                "index": 0,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Payment Data - Descriptive - Online LaTeX Editor Overleaf",
                "url": "https://www.overleaf.com/project/65806a19681ba1158b81219d",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://statics.teams.cdn.office.net/hashed/favicon/prod/favicon-f1722d9.ico",
                "groupId": 1058154117,
                "height": 1328,
                "highlighted": false,
                "id": 1388906329,
                "incognito": false,
                "index": 1,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "(1) PIER @ Teams | Microsoft Teams classic",
                "url": "https://teams.microsoft.com/_#/conversations/19:00e3666ae70e4ba1bc646e9bde7b62e6@thread.v2?ctx=chat",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": 1058154117,
                "height": 1328,
                "highlighted": false,
                "id": 1388906491,
                "incognito": false,
                "index": 2,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Amilamine edit blog 0101 by amilamine · Pull Request #576 · pier-x/pier-source",
                "url": "https://github.com/pier-x/pier-source/pull/576",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://res.cdn.office.net/owamail/20240119003.09/resources/images/favicons/mail-unseen.ico",
                "groupId": 1058154117,
                "height": 1328,
                "highlighted": false,
                "id": 1388906596,
                "incognito": false,
                "index": 3,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Mail - Thiti Tosborvorn (ฐิติ ทศบวร) - Outlook",
                "url": "https://outlook.office.com/mail/inbox/id/AAQkAGVhMzE3ZmQwLWI2ZWItNDczNi1hYjI1LTU3NGM1ZWQ5ZmFkYwAQAGD8Lgtvt0eIsfPXjCEeySo%3D",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906604,
                "incognito": false,
                "index": 4,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome window name - Google Search",
                "url": "https://www.google.com/search?q=chrome+window+name&rlz=1C5CHFA_enTH982TH982&oq=chrome+window+name&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyCAgBEAAYFhgeMggIAhAAGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yCAgHEAAYFhgeMggICBAAGBYYHjIICAkQABgWGB7SAQgyMzA1ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8#vhid=QFpaCcOlepqibM&vssid=l",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906607,
                "incognito": false,
                "index": 5,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome api window name - Google Search",
                "url": "https://www.google.com/search?q=chrome+api+window+name&rlz=1C5CHFA_enTH982TH982&oq=chrome+api+window+name&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yCAgCEAAYFhgeMg0IAxAAGIYDGIAEGIoFMg0IBBAAGIYDGIAEGIoF0gEIMzQxM2owajSoAgCwAgA&sourceid=chrome&ie=UTF-8",
                "width": 2165,
                "windowId": 1388900961
            },
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://bugs.chromium.org/static/images/monorail.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": true,
                "id": 1388906610,
                "incognito": false,
                "index": 6,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "1190160 - Programmatic access to window-name from chrome.windows extension API - chromium",
                "url": "https://bugs.chromium.org/p/chromium/issues/detail?id=1190160",
                "width": 2560,
                "windowId": 1388900961
            }
        ],
        "top": 25,
        "type": "normal",
        "width": 2560,
        "kind": "window",
        "children": [
            {
                "collapsed": false,
                "color": "yellow",
                "id": 1014996195,
                "title": "Development - Tools and IDEs",
                "windowId": 1388900961,
                "kind": "tabGroup",
                "children": [
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": false,
                        "favIconUrl": "https://www.overleaf.com/favicon.ico",
                        "groupId": 1014996195,
                        "height": 1328,
                        "highlighted": false,
                        "id": 1388904518,
                        "incognito": false,
                        "index": 0,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "complete",
                        "title": "Payment Data - Descriptive - Online LaTeX Editor Overleaf",
                        "url": "https://www.overleaf.com/project/65806a19681ba1158b81219d",
                        "width": 2165,
                        "windowId": 1388900961,
                        "kind": "tab",
                        "canHaveChildren": false
                    }
                ]
            },
            {
                "collapsed": false,
                "color": "orange",
                "id": 1058154117,
                "title": "Workplace Communication",
                "windowId": 1388900961,
                "kind": "tabGroup",
                "children": [
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": false,
                        "favIconUrl": "https://statics.teams.cdn.office.net/hashed/favicon/prod/favicon-f1722d9.ico",
                        "groupId": 1058154117,
                        "height": 1328,
                        "highlighted": false,
                        "id": 1388906329,
                        "incognito": false,
                        "index": 1,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "complete",
                        "title": "(1) PIER @ Teams | Microsoft Teams classic",
                        "url": "https://teams.microsoft.com/_#/conversations/19:00e3666ae70e4ba1bc646e9bde7b62e6@thread.v2?ctx=chat",
                        "width": 2165,
                        "windowId": 1388900961,
                        "kind": "tab",
                        "canHaveChildren": false
                    },
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": false,
                        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                        "groupId": 1058154117,
                        "height": 1328,
                        "highlighted": false,
                        "id": 1388906491,
                        "incognito": false,
                        "index": 2,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "complete",
                        "title": "Amilamine edit blog 0101 by amilamine · Pull Request #576 · pier-x/pier-source",
                        "url": "https://github.com/pier-x/pier-source/pull/576",
                        "width": 2165,
                        "windowId": 1388900961,
                        "kind": "tab",
                        "canHaveChildren": false
                    },
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": false,
                        "favIconUrl": "https://res.cdn.office.net/owamail/20240119003.09/resources/images/favicons/mail-unseen.ico",
                        "groupId": 1058154117,
                        "height": 1328,
                        "highlighted": false,
                        "id": 1388906596,
                        "incognito": false,
                        "index": 3,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "complete",
                        "title": "Mail - Thiti Tosborvorn (ฐิติ ทศบวร) - Outlook",
                        "url": "https://outlook.office.com/mail/inbox/id/AAQkAGVhMzE3ZmQwLWI2ZWItNDczNi1hYjI1LTU3NGM1ZWQ5ZmFkYwAQAGD8Lgtvt0eIsfPXjCEeySo%3D",
                        "width": 2165,
                        "windowId": 1388900961,
                        "kind": "tab",
                        "canHaveChildren": false
                    }
                ]
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906604,
                "incognito": false,
                "index": 4,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome window name - Google Search",
                "url": "https://www.google.com/search?q=chrome+window+name&rlz=1C5CHFA_enTH982TH982&oq=chrome+window+name&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyCAgBEAAYFhgeMggIAhAAGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yCAgHEAAYFhgeMggICBAAGBYYHjIICAkQABgWGB7SAQgyMzA1ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8#vhid=QFpaCcOlepqibM&vssid=l",
                "width": 2165,
                "windowId": 1388900961,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906607,
                "incognito": false,
                "index": 5,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome api window name - Google Search",
                "url": "https://www.google.com/search?q=chrome+api+window+name&rlz=1C5CHFA_enTH982TH982&oq=chrome+api+window+name&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yCAgCEAAYFhgeMg0IAxAAGIYDGIAEGIoFMg0IBBAAGIYDGIAEGIoF0gEIMzQxM2owajSoAgCwAgA&sourceid=chrome&ie=UTF-8",
                "width": 2165,
                "windowId": 1388900961,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://bugs.chromium.org/static/images/monorail.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": true,
                "id": 1388906610,
                "incognito": false,
                "index": 6,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "1190160 - Programmatic access to window-name from chrome.windows extension API - chromium",
                "url": "https://bugs.chromium.org/p/chromium/issues/detail?id=1190160",
                "width": 2560,
                "windowId": 1388900961,
                "kind": "tab",
                "canHaveChildren": false
            }
        ]
    },
    {
        "alwaysOnTop": false,
        "focused": true,
        "height": 1415,
        "id": 1388902663,
        "incognito": false,
        "left": 1512,
        "state": "maximized",
        "tabs": [
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": true,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": 738097822,
                "height": 0,
                "highlighted": false,
                "id": 1388906657,
                "incognito": false,
                "index": 0,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "unloaded",
                "title": "react component label click rename - Google Search",
                "url": "https://www.google.com/search?q=react+component+label+click+rename&rlz=1C5CHFA_enTH982TH982&oq=react+component+label+click+rename&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDg1NDVqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",
                "width": 0,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": 738097822,
                "height": 857,
                "highlighted": false,
                "id": 1388905407,
                "incognito": false,
                "index": 1,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Shaddix/dnd-kit-sortable-tree at ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                "url": "https://github.com/Shaddix/dnd-kit-sortable-tree/tree/ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                "width": 1512,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905148,
                "incognito": false,
                "index": 2,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "ChatGPT - DALL·E",
                "url": "https://chat.openai.com/g/g-2fkFE8rbu-dall-e/c/d26e1592-1340-4d3a-920b-a97fdeee38d2",
                "width": 2560,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": true,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 0,
                "highlighted": false,
                "id": 1388906052,
                "incognito": false,
                "index": 3,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "unloaded",
                "title": "clauderic/dnd-kit: The modern, lightweight, performant, accessible and extensible drag & drop toolkit for React.",
                "url": "https://github.com/clauderic/dnd-kit?tab=readme-ov-file",
                "width": 0,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": true,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 0,
                "highlighted": false,
                "id": 1388906055,
                "incognito": false,
                "index": 4,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "unloaded",
                "title": "dnd-kit/playground at master · clauderic/dnd-kit",
                "url": "https://github.com/clauderic/dnd-kit/tree/master/playground",
                "width": 0,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905903,
                "incognito": false,
                "index": 5,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "dnd-kit/stories/2 - Presets/Sortable/MultipleContainers.tsx at master · clauderic/dnd-kit",
                "url": "https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906119,
                "incognito": false,
                "index": 6,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Presets / Sortable / Multiple Containers - Vertical ⋅ Storybook",
                "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--vertical",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906075,
                "incognito": false,
                "index": 7,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "vite \"css modules\" site:stackoverflow.com - Google Search",
                "url": "https://www.google.com/search?q=vite+%22css+modules%22+site%3Astackoverflow.com&sca_esv=601029419&rlz=1C5CHFA_enTH982TH982&biw=2560&bih=1328&sxsrf=ACQVn0_ZbL4e6Ovx-4ddTVxGG84SnFOKkA%3A1706088294296&ei=ZtewZbPYEdKfseMPw8KT2As&ved=0ahUKEwizo_KV2vWDAxXST2wGHUPhBLsQ4dUDCBA&uact=5&oq=vite+%22css+modules%22+site%3Astackoverflow.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKXZpdGUgImNzcyBtb2R1bGVzIiBzaXRlOnN0YWNrb3ZlcmZsb3cuY29tSI0XUOYHWIIVcAF4AJABAJgBS6ABkwGqAQEyuAEDyAEA-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp",
                "width": 2560,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906078,
                "incognito": false,
                "index": 8,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Vite + Sass + CSS Modules: `composes` prop limitation - Stack Overflow",
                "url": "https://stackoverflow.com/questions/75243712/vite-sass-css-modules-composes-prop-limitation",
                "width": 2560,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905941,
                "incognito": false,
                "index": 9,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "reactjs - Scope CSS with React + Vite - Stack Overflow",
                "url": "https://stackoverflow.com/questions/77061660/scope-css-with-react-vite",
                "width": 2560,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906518,
                "incognito": false,
                "index": 10,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Amilamine edit blog 0101 by amilamine · Pull Request #576 · pier-x/pier-source",
                "url": "https://github.com/pier-x/pier-source/pull/576",
                "width": 2560,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.gstatic.com/devrel-devsite/prod/vb47a36f3a983ed748bf281529457db47955fe57e2b5ea15e7e9641c5e7b5032e/chrome/images/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906622,
                "incognito": false,
                "index": 11,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome.tabs  |  API  |  Chrome for Developers",
                "url": "https://developer.chrome.com/docs/extensions/reference/api/tabs#method-move",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906625,
                "incognito": false,
                "index": 12,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "lightweight react ui library - Google Search",
                "url": "https://www.google.com/search?q=lightweight+react+ui+library&rlz=1C5CHFA_enTH982TH982&oq=lightweight+react+ui+&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBggBEEUYOTIICAIQABgWGB4yDQgDEAAYhgMYgAQYigUyDQgEEAAYhgMYgAQYigWoAgCwAgA&sourceid=chrome&ie=UTF-8",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.redditstatic.com/desktop2x/img/favicon/favicon-32x32.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906628,
                "incognito": false,
                "index": 13,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Reddit - Dive into anything",
                "url": "https://www.reddit.com/r/reactjs/comments/s7ghxq/looking_for_a_lightweight_component_library/",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://chakra-ui.com/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906629,
                "incognito": false,
                "index": 14,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Button - Chakra UI",
                "url": "https://chakra-ui.com/docs/components/button/theming",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://copyprogramming.com/themes/favicon-32x32.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906638,
                "incognito": false,
                "index": 15,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Npm: Using a Separate package.json File for npm install",
                "url": "https://copyprogramming.com/howto/npm-install-use-different-package-json-file",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906649,
                "incognito": false,
                "index": 16,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Extensions",
                "url": "chrome://extensions/",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://chakra-ui.com/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906654,
                "incognito": false,
                "index": 17,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Input - Chakra UI",
                "url": "https://chakra-ui.com/docs/components/input#controlled-input",
                "width": 2165,
                "windowId": 1388902663
            },
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "http://localhost:5173/vite.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": true,
                "id": 1388906660,
                "incognito": false,
                "index": 18,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "Vite + React + TS",
                "url": "http://localhost:5173/",
                "width": 2165,
                "windowId": 1388902663
            }
        ],
        "top": 25,
        "type": "normal",
        "width": 2560,
        "kind": "window",
        "children": [
            {
                "collapsed": false,
                "color": "yellow",
                "id": 738097822,
                "title": "React Component & ESLint Information",
                "windowId": 1388902663,
                "kind": "tabGroup",
                "children": [
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": true,
                        "favIconUrl": "https://www.google.com/favicon.ico",
                        "groupId": 738097822,
                        "height": 0,
                        "highlighted": false,
                        "id": 1388906657,
                        "incognito": false,
                        "index": 0,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "unloaded",
                        "title": "react component label click rename - Google Search",
                        "url": "https://www.google.com/search?q=react+component+label+click+rename&rlz=1C5CHFA_enTH982TH982&oq=react+component+label+click+rename&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDg1NDVqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8",
                        "width": 0,
                        "windowId": 1388902663,
                        "kind": "tab",
                        "canHaveChildren": false
                    },
                    {
                        "active": false,
                        "audible": false,
                        "autoDiscardable": true,
                        "discarded": false,
                        "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                        "groupId": 738097822,
                        "height": 857,
                        "highlighted": false,
                        "id": 1388905407,
                        "incognito": false,
                        "index": 1,
                        "mutedInfo": {
                            "muted": false
                        },
                        "pinned": false,
                        "selected": false,
                        "status": "complete",
                        "title": "Shaddix/dnd-kit-sortable-tree at ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                        "url": "https://github.com/Shaddix/dnd-kit-sortable-tree/tree/ba2adc8f1df9b5d0ecced5199cfe51587b3e806c",
                        "width": 1512,
                        "windowId": 1388902663,
                        "kind": "tab",
                        "canHaveChildren": false
                    }
                ]
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905148,
                "incognito": false,
                "index": 2,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "ChatGPT - DALL·E",
                "url": "https://chat.openai.com/g/g-2fkFE8rbu-dall-e/c/d26e1592-1340-4d3a-920b-a97fdeee38d2",
                "width": 2560,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": true,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 0,
                "highlighted": false,
                "id": 1388906052,
                "incognito": false,
                "index": 3,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "unloaded",
                "title": "clauderic/dnd-kit: The modern, lightweight, performant, accessible and extensible drag & drop toolkit for React.",
                "url": "https://github.com/clauderic/dnd-kit?tab=readme-ov-file",
                "width": 0,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": true,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 0,
                "highlighted": false,
                "id": 1388906055,
                "incognito": false,
                "index": 4,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "unloaded",
                "title": "dnd-kit/playground at master · clauderic/dnd-kit",
                "url": "https://github.com/clauderic/dnd-kit/tree/master/playground",
                "width": 0,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905903,
                "incognito": false,
                "index": 5,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "dnd-kit/stories/2 - Presets/Sortable/MultipleContainers.tsx at master · clauderic/dnd-kit",
                "url": "https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906119,
                "incognito": false,
                "index": 6,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Presets / Sortable / Multiple Containers - Vertical ⋅ Storybook",
                "url": "https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--vertical",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906075,
                "incognito": false,
                "index": 7,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "vite \"css modules\" site:stackoverflow.com - Google Search",
                "url": "https://www.google.com/search?q=vite+%22css+modules%22+site%3Astackoverflow.com&sca_esv=601029419&rlz=1C5CHFA_enTH982TH982&biw=2560&bih=1328&sxsrf=ACQVn0_ZbL4e6Ovx-4ddTVxGG84SnFOKkA%3A1706088294296&ei=ZtewZbPYEdKfseMPw8KT2As&ved=0ahUKEwizo_KV2vWDAxXST2wGHUPhBLsQ4dUDCBA&uact=5&oq=vite+%22css+modules%22+site%3Astackoverflow.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKXZpdGUgImNzcyBtb2R1bGVzIiBzaXRlOnN0YWNrb3ZlcmZsb3cuY29tSI0XUOYHWIIVcAF4AJABAJgBS6ABkwGqAQEyuAEDyAEA-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp",
                "width": 2560,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906078,
                "incognito": false,
                "index": 8,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Vite + Sass + CSS Modules: `composes` prop limitation - Stack Overflow",
                "url": "https://stackoverflow.com/questions/75243712/vite-sass-css-modules-composes-prop-limitation",
                "width": 2560,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388905941,
                "incognito": false,
                "index": 9,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "reactjs - Scope CSS with React + Vite - Stack Overflow",
                "url": "https://stackoverflow.com/questions/77061660/scope-css-with-react-vite",
                "width": 2560,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906518,
                "incognito": false,
                "index": 10,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Amilamine edit blog 0101 by amilamine · Pull Request #576 · pier-x/pier-source",
                "url": "https://github.com/pier-x/pier-source/pull/576",
                "width": 2560,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.gstatic.com/devrel-devsite/prod/vb47a36f3a983ed748bf281529457db47955fe57e2b5ea15e7e9641c5e7b5032e/chrome/images/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906622,
                "incognito": false,
                "index": 11,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "chrome.tabs  |  API  |  Chrome for Developers",
                "url": "https://developer.chrome.com/docs/extensions/reference/api/tabs#method-move",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.google.com/favicon.ico",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906625,
                "incognito": false,
                "index": 12,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "lightweight react ui library - Google Search",
                "url": "https://www.google.com/search?q=lightweight+react+ui+library&rlz=1C5CHFA_enTH982TH982&oq=lightweight+react+ui+&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBggBEEUYOTIICAIQABgWGB4yDQgDEAAYhgMYgAQYigUyDQgEEAAYhgMYgAQYigWoAgCwAgA&sourceid=chrome&ie=UTF-8",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://www.redditstatic.com/desktop2x/img/favicon/favicon-32x32.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906628,
                "incognito": false,
                "index": 13,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Reddit - Dive into anything",
                "url": "https://www.reddit.com/r/reactjs/comments/s7ghxq/looking_for_a_lightweight_component_library/",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://chakra-ui.com/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906629,
                "incognito": false,
                "index": 14,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Button - Chakra UI",
                "url": "https://chakra-ui.com/docs/components/button/theming",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://copyprogramming.com/themes/favicon-32x32.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906638,
                "incognito": false,
                "index": 15,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Npm: Using a Separate package.json File for npm install",
                "url": "https://copyprogramming.com/howto/npm-install-use-different-package-json-file",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906649,
                "incognito": false,
                "index": 16,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Extensions",
                "url": "chrome://extensions/",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": false,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "https://chakra-ui.com/favicon.png",
                "groupId": -1,
                "height": 1328,
                "highlighted": false,
                "id": 1388906654,
                "incognito": false,
                "index": 17,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": false,
                "status": "complete",
                "title": "Input - Chakra UI",
                "url": "https://chakra-ui.com/docs/components/input#controlled-input",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            },
            {
                "active": true,
                "audible": false,
                "autoDiscardable": true,
                "discarded": false,
                "favIconUrl": "http://localhost:5173/vite.svg",
                "groupId": -1,
                "height": 1328,
                "highlighted": true,
                "id": 1388906660,
                "incognito": false,
                "index": 18,
                "mutedInfo": {
                    "muted": false
                },
                "pinned": false,
                "selected": true,
                "status": "complete",
                "title": "Vite + React + TS",
                "url": "http://localhost:5173/",
                "width": 2165,
                "windowId": 1388902663,
                "kind": "tab",
                "canHaveChildren": false
            }
        ]
    }
]