export const data = [
  {
      "alwaysOnTop": false,
      "focused": false,
      "height": 944,
      "id": 1388902663,
      "incognito": false,
      "left": 0,
      "state": "normal",
      "tabs": [
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388907910,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "ChatGPT - NongHed",
              "url": "https://chat.openai.com/g/g-JTWFaCNHI-nonghed/c/985c0aa9-accd-419e-a432-c513ccaa4f0f",
              "width": 1117,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": 2059644940,
              "height": 0,
              "highlighted": false,
              "id": 1388908297,
              "incognito": false,
              "index": 1,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Collision detection algorithms - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": 2059644940,
              "height": 0,
              "highlighted": false,
              "id": 1388908300,
              "incognito": false,
              "index": 2,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "useDroppable - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/api-documentation/droppable/usedroppable",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
              "groupId": 2059644940,
              "height": 857,
              "highlighted": false,
              "id": 1388908303,
              "incognito": false,
              "index": 3,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Installation - @dnd-kit – Documentation",
              "url": "https://docs.dndkit.com/introduction/installation",
              "width": 1117,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://ssl.gstatic.com/docs/documents/images/kix-favicon-2023q4.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388908026,
              "incognito": false,
              "index": 4,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "A40 Exploration - Google Docs",
              "url": "https://docs.google.com/document/d/1KmoHA-S_9ePZAjow-laWfpKTh79zCvDfwmVEyMdr8VU/edit",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://ssl.gstatic.com/docs/spreadsheets/spreadsheets_2023q4.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388907683,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Untitled spreadsheet - Google Sheets",
              "url": "https://docs.google.com/spreadsheets/d/1UEljqJyOIc0GJqz_-KyGVHv0h8v14d0M7L6HUgBRnPQ/edit#gid=0",
              "width": 2560,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon-dark.svg",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388908310,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "dnd-kit/stories/2 - Presets/Sortable/MultipleContainers.tsx at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx",
              "width": 1117,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388908313,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Nested Multiple Containers · Issue #735 · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/issues/735",
              "width": 0,
              "windowId": 1388902663
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://static-production.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388908590,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "@crxjs/vite-plugin - npm",
              "url": "https://www.npmjs.com/package/@crxjs/vite-plugin",
              "width": 361,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon-dark.svg",
              "groupId": 1526285374,
              "height": 857,
              "highlighted": false,
              "id": 1388908593,
              "incognito": false,
              "index": 9,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "crxjs/chrome-extension-tools: Bundling Chrome Extensions can be pretty complex. It doesn't have to be.",
              "url": "https://github.com/crxjs/chrome-extension-tools",
              "width": 1117,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://abs.twimg.com/favicons/twitter.3.ico",
              "groupId": 1526285374,
              "height": 857,
              "highlighted": false,
              "id": 1388908599,
              "incognito": false,
              "index": 10,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Home / X",
              "url": "https://twitter.com/home",
              "width": 1512,
              "windowId": 1388902663
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://blog.logrocket.com/wp-content/uploads/2019/06/cropped-cropped-favicon-196x196.png?w=32",
              "groupId": 1526285374,
              "height": 857,
              "highlighted": false,
              "id": 1388908602,
              "incognito": false,
              "index": 11,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "TypeScript enums vs. types: Enhancing code readability - LogRocket Blog",
              "url": "https://blog.logrocket.com/typescript-enums-vs-types/#:~:text=Use%20string%20enums%3A%20If%20possible,bitwise%20operations%2C%20use%20numeric%20enums",
              "width": 1512,
              "windowId": 1388902663
          }
      ],
      "top": 38,
      "type": "normal",
      "width": 756,
      "parentId": null,
      "kind": "window",
      "children": [
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://cdn.oaistatic.com/_next/static/media/favicon-32x32.be48395e.png",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388907910,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "ChatGPT - NongHed",
              "url": "https://chat.openai.com/g/g-JTWFaCNHI-nonghed/c/985c0aa9-accd-419e-a432-c513ccaa4f0f",
              "width": 1117,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "collapsed": false,
              "color": "yellow",
              "id": 2059644940,
              "title": "@dnd-kit Documentation",
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": true,
                      "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
                      "groupId": 2059644940,
                      "height": 0,
                      "highlighted": false,
                      "id": 1388908297,
                      "incognito": false,
                      "index": 1,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "unloaded",
                      "title": "Collision detection algorithms - @dnd-kit – Documentation",
                      "url": "https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms",
                      "width": 0,
                      "windowId": 1388902663,
                      "parentId": 2059644940,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": true,
                      "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
                      "groupId": 2059644940,
                      "height": 0,
                      "highlighted": false,
                      "id": 1388908300,
                      "incognito": false,
                      "index": 2,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "unloaded",
                      "title": "useDroppable - @dnd-kit – Documentation",
                      "url": "https://docs.dndkit.com/api-documentation/droppable/usedroppable",
                      "width": 0,
                      "windowId": 1388902663,
                      "parentId": 2059644940,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://584762767-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MMujhzqaYbBEEmDxnZO%2Ficon%2FVvBxfRINGV7cyEEdBv5o%2FPage%201%20(2).png?alt=media&token=7fe97f03-3eac-4139-a046-7106ce9305c3",
                      "groupId": 2059644940,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388908303,
                      "incognito": false,
                      "index": 3,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "Installation - @dnd-kit – Documentation",
                      "url": "https://docs.dndkit.com/introduction/installation",
                      "width": 1117,
                      "windowId": 1388902663,
                      "parentId": 2059644940,
                      "kind": "tab",
                      "children": []
                  }
              ]
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://ssl.gstatic.com/docs/documents/images/kix-favicon-2023q4.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388908026,
              "incognito": false,
              "index": 4,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "A40 Exploration - Google Docs",
              "url": "https://docs.google.com/document/d/1KmoHA-S_9ePZAjow-laWfpKTh79zCvDfwmVEyMdr8VU/edit",
              "width": 2560,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://ssl.gstatic.com/docs/spreadsheets/spreadsheets_2023q4.ico",
              "groupId": -1,
              "height": 1328,
              "highlighted": false,
              "id": 1388907683,
              "incognito": false,
              "index": 5,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Untitled spreadsheet - Google Sheets",
              "url": "https://docs.google.com/spreadsheets/d/1UEljqJyOIc0GJqz_-KyGVHv0h8v14d0M7L6HUgBRnPQ/edit#gid=0",
              "width": 2560,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon-dark.svg",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388908310,
              "incognito": false,
              "index": 6,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "dnd-kit/stories/2 - Presets/Sortable/MultipleContainers.tsx at master · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/blob/master/stories/2%20-%20Presets/Sortable/MultipleContainers.tsx",
              "width": 1117,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": true,
              "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
              "groupId": -1,
              "height": 0,
              "highlighted": false,
              "id": 1388908313,
              "incognito": false,
              "index": 7,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "unloaded",
              "title": "Nested Multiple Containers · Issue #735 · clauderic/dnd-kit",
              "url": "https://github.com/clauderic/dnd-kit/issues/735",
              "width": 0,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://static-production.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388908590,
              "incognito": false,
              "index": 8,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "@crxjs/vite-plugin - npm",
              "url": "https://www.npmjs.com/package/@crxjs/vite-plugin",
              "width": 361,
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tab",
              "children": []
          },
          {
              "collapsed": false,
              "color": "blue",
              "id": 1526285374,
              "title": "Chrome Extension Development",
              "windowId": 1388902663,
              "parentId": 1388902663,
              "kind": "tabGroup",
              "children": [
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://github.githubassets.com/favicons/favicon-dark.svg",
                      "groupId": 1526285374,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388908593,
                      "incognito": false,
                      "index": 9,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "crxjs/chrome-extension-tools: Bundling Chrome Extensions can be pretty complex. It doesn't have to be.",
                      "url": "https://github.com/crxjs/chrome-extension-tools",
                      "width": 1117,
                      "windowId": 1388902663,
                      "parentId": 1526285374,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://abs.twimg.com/favicons/twitter.3.ico",
                      "groupId": 1526285374,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388908599,
                      "incognito": false,
                      "index": 10,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "Home / X",
                      "url": "https://twitter.com/home",
                      "width": 1512,
                      "windowId": 1388902663,
                      "parentId": 1526285374,
                      "kind": "tab",
                      "children": []
                  },
                  {
                      "active": false,
                      "audible": false,
                      "autoDiscardable": true,
                      "discarded": false,
                      "favIconUrl": "https://blog.logrocket.com/wp-content/uploads/2019/06/cropped-cropped-favicon-196x196.png?w=32",
                      "groupId": 1526285374,
                      "height": 857,
                      "highlighted": false,
                      "id": 1388908602,
                      "incognito": false,
                      "index": 11,
                      "mutedInfo": {
                          "muted": false
                      },
                      "pinned": false,
                      "selected": false,
                      "status": "complete",
                      "title": "TypeScript enums vs. types: Enhancing code readability - LogRocket Blog",
                      "url": "https://blog.logrocket.com/typescript-enums-vs-types/#:~:text=Use%20string%20enums%3A%20If%20possible,bitwise%20operations%2C%20use%20numeric%20enums",
                      "width": 1512,
                      "windowId": 1388902663,
                      "parentId": 1526285374,
                      "kind": "tab",
                      "children": []
                  }
              ]
          }
      ]
  },
  {
      "alwaysOnTop": false,
      "focused": false,
      "height": 944,
      "id": 1388908617,
      "incognito": false,
      "left": 756,
      "state": "normal",
      "tabs": [
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://9gag.com/favicon.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388908294,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "9GAG - Best Funny Memes and Breaking News",
              "url": "https://9gag.com/",
              "width": 361,
              "windowId": 1388908617
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388908614,
              "incognito": false,
              "index": 1,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Extensions",
              "url": "chrome://extensions/",
              "width": 1117,
              "windowId": 1388908617
          }
      ],
      "top": 38,
      "type": "normal",
      "width": 756,
      "parentId": null,
      "kind": "window",
      "children": [
          {
              "active": true,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "https://9gag.com/favicon.ico",
              "groupId": -1,
              "height": 857,
              "highlighted": true,
              "id": 1388908294,
              "incognito": false,
              "index": 0,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": true,
              "status": "complete",
              "title": "9GAG - Best Funny Memes and Breaking News",
              "url": "https://9gag.com/",
              "width": 361,
              "windowId": 1388908617,
              "parentId": 1388908617,
              "kind": "tab",
              "children": []
          },
          {
              "active": false,
              "audible": false,
              "autoDiscardable": true,
              "discarded": false,
              "favIconUrl": "",
              "groupId": -1,
              "height": 857,
              "highlighted": false,
              "id": 1388908614,
              "incognito": false,
              "index": 1,
              "mutedInfo": {
                  "muted": false
              },
              "pinned": false,
              "selected": false,
              "status": "complete",
              "title": "Extensions",
              "url": "chrome://extensions/",
              "width": 1117,
              "windowId": 1388908617,
              "parentId": 1388908617,
              "kind": "tab",
              "children": []
          }
      ]
  }
]